# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class S3ry < Formula
  desc "Modern High-Performance S3 CLI Tool with 10x performance improvement"
  homepage "https://github.com/seike460/s3ry"
  version "2.0.0"
  license "MIT"

  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/seike460/s3ry/releases/download/v2.0.0/s3ry_Darwin_x86_64.tar.gz"
      sha256 "1730ed9cd624ed12519e8da251e0380294e890f04dff64fcc26efbf55ff69036"

      def install
        bin.install "s3ry"

        # Generate shell completions
        generate_completions_from_executable(bin/"s3ry", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/seike460/s3ry/releases/download/v2.0.0/s3ry_Darwin_arm64.tar.gz"
      sha256 "07dbbba82054fd5d7fa259898caebb55c6cef4ff7379455eed8688d056747d41"

      def install
        bin.install "s3ry"

        # Generate shell completions
        generate_completions_from_executable(bin/"s3ry", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/seike460/s3ry/releases/download/v2.0.0/s3ry_Linux_x86_64.tar.gz"
        sha256 "d17b8c048634a0bc922d8997d1cf77a4773bfd1b49bffd6716cbd907c3550a3c"

        def install
          bin.install "s3ry"

          # Generate shell completions
          generate_completions_from_executable(bin/"s3ry", "completion")
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/seike460/s3ry/releases/download/v2.0.0/s3ry_Linux_armv6.tar.gz"
        sha256 "0683061ffc764d433b36c8b17ac64375a20c2b80e2a9523e07271ecf9c7b12f2"

        def install
          bin.install "s3ry"

          # Generate shell completions
          generate_completions_from_executable(bin/"s3ry", "completion")
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/seike460/s3ry/releases/download/v2.0.0/s3ry_Linux_arm64.tar.gz"
        sha256 "6b8256858f79c9856d646bbf18d359700144de2d2f35d5a492da86e519a6b863"

        def install
          bin.install "s3ry"

          # Generate shell completions
          generate_completions_from_executable(bin/"s3ry", "completion")
        end
      end
    end
  end

  test do
    system "#{bin}/s3ry", "version"
  end
end
