# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class S3ry < Formula
  desc "Modern High-Performance S3 CLI Tool with 10x performance improvement"
  homepage "https://github.com/seike460/s3ry"
  version "2.0.0"
  license "MIT"

  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/seike460/s3ry/releases/download/v2.0.0/s3ry_Darwin_x86_64.tar.gz"
      sha256 "79e190d1ef495281c7cb7d684591656261437058b87a2a50d00eee588fd707db"

      def install
        bin.install "s3ry"

      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/seike460/s3ry/releases/download/v2.0.0/s3ry_Darwin_arm64.tar.gz"
      sha256 "b99ba246961b1b3c57d7ed2793ff223a55434e1051d8841bb4b7c51e8c021990"

      def install
        bin.install "s3ry"

      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/seike460/s3ry/releases/download/v2.0.0/s3ry_Linux_x86_64.tar.gz"
        sha256 "4bf12910f12cfe3e79eeff865c57d044e10190b833edd0656cd9061d92c27984"

        def install
          bin.install "s3ry"

        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/seike460/s3ry/releases/download/v2.0.0/s3ry_Linux_armv6.tar.gz"
        sha256 "435c464427241ef839063349ed38b5f6075cff176c32a1c46954349b975838a2"

        def install
          bin.install "s3ry"

        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/seike460/s3ry/releases/download/v2.0.0/s3ry_Linux_arm64.tar.gz"
        sha256 "b84ef5869d45126d84a6959bc1e6db0be6d2dd7a5e72c0158823ef0b72d99891"

        def install
          bin.install "s3ry"

        end
      end
    end
  end

  test do
    system "#{bin}/s3ry", "version"
  end
end
